<?php
    $servername = "localhost";
    $username = "root";
    $password = "";
    $dbname = "smet_core_database";
	
	// Create connection
	$conn = mysqli_connect($servername, $username, $password, $dbname);
	
	// Check connection
	if (!$conn) {
		die("Connection failed: " . mysqli_connect_error());
	}
	
	$to = $_POST['femail'];	
	$id = mysqli_query($conn,"SELECT company_id FROM registration WHERE email_address = '".$to."'")->fetch_object()->company_id;
	//var_dump($id);
	//exit();
	
	
//	$res[] = mysql_result($id, 0 );
	//var_dump($res);
	
	
	
	
	mysqli_close($conn);
	$email_exp = '/^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$/';
	if(!preg_match($email_exp,$to)) {
			echo "mailn";
			exit();
		}
	if($id == NULL){
		echo "mailn";
		exit();
	}
	
	if ($id != NULL) {
		
		
		
		if ( function_exists('mail') ){
			$subject = 'SMET - [Company ID]'; 
			$message = "Dear User,\n\nThis email is to inform you that the company ID information is requested on your behalf. ID registered against your email is: '.$id.'\n\nFor any further query, please use 'Contact Us' form.\n\n\nDisclaimer:\nThis is an autogenerated email and contains confidential information intended only for the use of addressee."; 
			$headers = "From: scrum.evaluator@gmail.com\r\nReply-To: scrum.evaluator@gmail.com";
			$mail_sent = mail( $to, $subject, $message, $headers );
			echo $mail_sent ? "success" : "mail";
		}
		else {
		   echo "mail";
		}
	}
	
	else {
		echo "error";
	}	
?>
