<?php
    $servername = "localhost";
    $username = "root";
    $password = "";
    $dbname = "smet_core_database";
	
	// Create connection
	$conn = mysqli_connect($servername, $username, $password, $dbname);
	
	// Check connection
	if (!$conn) {
		die("Connection failed: " . mysqli_connect_error());
	}
	
	$to = $_POST['genid'];
	
	$id = mysqli_query($conn,"SELECT company_id FROM registration WHERE email_address = '".$to."'")->fetch_assoc();
	echo $id;
	
	$id = mysqli_query($conn,"SELECT company_id FROM registration WHERE email_address = '".$to."'")->fetch_object()->company_id;
	echo $id;
	
	if ($id != NULL) {
		
		mysqli_close($conn);
		echo "error";
				
	}
	else {
		
		$sql = mysqli_query($conn, "INSERT IGNORE INTO `regiteration`(`email_address`) VALUES ('$t')");
		$nid = mysqli_query($conn,"SELECT company_id FROM registration WHERE email_address = '".$to."'")->fetch_object()->company_id;
		echo $nid;
		mysqli_close($conn);
		$subject = 'SMET - [Company ID]'; 
		//$message = "Dear User,\n\nThis email is to inform you that the company ID information is requested on your behalf.ID registered against your email is: '.$nid.'\n\nFor any further query, please use 'Contact Us' form.\n\n\nDisclaimer:\nThis is an autogenerated email and contains confidential information intended only for the use of addressee."; 
		//$message = "Dear User,\n\nThis email is to inform you that the company ID information is requested on your behalf. ID registered against your email is: '.$nid.'\n\nFor any further query, please use 'Contact Us' form.\n\n\nDisclaimer:\nThis is an autogenerated email and contains confidential information intended only for the use of addressee."; 
		$message = "Dear User,\n\nThis email is to inform you that the Company registeration is requested on your behalf. ID registered against your email is: '.$nid.'\n\nFor any further query, please use 'Contact Us' form.\n\n\nDisclaimer:\nThis is an autogenerated email and contains confidential information intended only for the use of addressee."; 
			
		$headers = "MIME-Version: 1.0" . "\r\n";
		$headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";
		$headers .= "From: scrum.evaluator@gmail.com";
		$mail_sent= mail($to,$subject,$message, $headers);
		
		echo $mail_sent ? "success" : "error";
		
	}	
?>
