<?php
	if ( function_exists( 'mail') ){
		echo 'mail() is enable';
		$to = 'scrum.evaluator@gmail.com';
		$subject = 'SMET - [Company ID]'; 
		$message = "Dear User,\n\nThis email is to inform you that the company ID information is requested on your behalf. ID registered against your email is: 123789 \n\nFor any further query, please use Contact Us form.\n\n\nDisclaimer:\nThis is an autogenerated email and contains confidential information intended only for the use of addressee."; 
		$headers = "From: scrum.evaluator@gmail.com\r\nReply-To: scrum.evaluator@gmail.com";
		$mail_sent = mail( $to, $subject, $message, $headers );
		echo $mail_sent ? "Mail sent" : "Mail failed";
		
		/*$to         = $email; //replace with your email
		$subject    = 'SMET - [Company ID]'; 
		$message    = 'Dear User,\n\n This email is to inform you that the company ID information is requested on your behalf. ID registered against your email is: '.$id.'\n\n For any further query, please use "Contact Us" form.\n\n\n Disclaimer:\nThis is an autogenerated email and contains confidential information intended only for the use of addressee.'; 

		$headers = "MIME-Version: 1.0" . "\r\n";
		$headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";
		$headers .= "From: scrum.evaluator@gmail.com";
		$mail_sent = mail($to,$subject,$message, $headers);
		
		echo $mail_sent ? "success" : "error";*/
		
	}
	else
	   echo 'mail() has been disabled';
	   exit();
?>
